//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for EstadoCatalogo.
const (
	Activo   EstadoCatalogo = "activo"
	Inactivo EstadoCatalogo = "inactivo"
)

// Valid indicates whether the value is a known member of the EstadoCatalogo enum.
func (e EstadoCatalogo) Valid() bool {
	switch e {
	case Activo:
		return true
	case Inactivo:
		return true
	default:
		return false
	}
}

// Defines values for EstadoReserva.
const (
	Cancelada  EstadoReserva = "cancelada"
	Completada EstadoReserva = "completada"
	Confirmada EstadoReserva = "confirmada"
	EnCurso    EstadoReserva = "en_curso"
	Expirada   EstadoReserva = "expirada"
	NoShow     EstadoReserva = "no_show"
	Pendiente  EstadoReserva = "pendiente"
)

// Valid indicates whether the value is a known member of the EstadoReserva enum.
func (e EstadoReserva) Valid() bool {
	switch e {
	case Cancelada:
		return true
	case Completada:
		return true
	case Confirmada:
		return true
	case EnCurso:
		return true
	case Expirada:
		return true
	case NoShow:
		return true
	case Pendiente:
		return true
	default:
		return false
	}
}

// Contacto defines model for Contacto.
type Contacto struct {
	Email    openapi_types.Email `json:"email"`
	Nombre   string              `json:"nombre"`
	Telefono *string             `json:"telefono,omitempty"`
}

// Dinero El monto va como cadena decimal, no como número. En JSON los números son
// de coma flotante y 80000.10 no se representa exactamente; con dinero eso
// acaba en un céntimo de diferencia entre lo que se cobra y lo que se
// muestra. La columna del esquema es `numeric`, que sí es exacta, y una
// cadena la preserva de extremo a extremo.
type Dinero struct {
	// Moneda Código ISO 4217.
	//
	// Examples: COP
	Moneda string `json:"moneda"`

	// Monto Examples: 80000.00
	Monto string `json:"monto"`
}

// Disponibilidad defines model for Disponibilidad.
type Disponibilidad struct {
	// CalculadaEn Cuándo se calculó esta vista. El cliente puede saber así cuánta
	// desactualización está viendo, dentro de los 2 s que RNF-10 permite.
	CalculadaEn time.Time          `json:"calculada_en"`
	Franjas     []Franja           `json:"franjas"`
	ServicioId  openapi_types.UUID `json:"servicio_id"`
}

// EstadoCatalogo defines model for EstadoCatalogo.
type EstadoCatalogo string

// EstadoReserva Estados de RF-28.
type EstadoReserva string

// Franja defines model for Franja.
type Franja struct {
	// Periodo Intervalo semiabierto `[inicio, fin)`. El límite inferior entra, el
	// superior no.
	//
	// No es un detalle de estilo: con ambos límites cerrados, 10:00–11:00 y
	// 11:00–12:00 comparten un instante, el operador `&&` de PostgreSQL las
	// declara solapadas y la restricción EXCLUDE rechazaría dos citas
	// consecutivas perfectamente válidas.
	Periodo   Periodo            `json:"periodo"`
	RecursoId openapi_types.UUID `json:"recurso_id"`
}

// ListaReservas defines model for ListaReservas.
type ListaReservas struct {
	Datos []Reserva `json:"datos"`

	// SiguienteCursor Ausente cuando no hay más páginas.
	SiguienteCursor *string `json:"siguiente_cursor,omitempty"`
}

// ListaSedes defines model for ListaSedes.
type ListaSedes struct {
	Datos []Sede `json:"datos"`
}

// ListaServicios defines model for ListaServicios.
type ListaServicios struct {
	Datos []Servicio `json:"datos"`
}

// NuevaReserva defines model for NuevaReserva.
type NuevaReserva struct {
	Contacto Contacto `json:"contacto"`

	// Periodo Intervalo semiabierto `[inicio, fin)`. El límite inferior entra, el
	// superior no.
	//
	// No es un detalle de estilo: con ambos límites cerrados, 10:00–11:00 y
	// 11:00–12:00 comparten un instante, el operador `&&` de PostgreSQL las
	// declara solapadas y la restricción EXCLUDE rechazaría dos citas
	// consecutivas perfectamente válidas.
	Periodo    Periodo            `json:"periodo"`
	RecursoId  openapi_types.UUID `json:"recurso_id"`
	ServicioId openapi_types.UUID `json:"servicio_id"`

	// VoucherCodigo Código de descuento, si aplica (RF-08).
	VoucherCodigo *string `json:"voucher_codigo,omitempty"`
}

// Periodo Intervalo semiabierto `[inicio, fin)`. El límite inferior entra, el
// superior no.
//
// No es un detalle de estilo: con ambos límites cerrados, 10:00–11:00 y
// 11:00–12:00 comparten un instante, el operador `&&` de PostgreSQL las
// declara solapadas y la restricción EXCLUDE rechazaría dos citas
// consecutivas perfectamente válidas.
type Periodo struct {
	Fin    time.Time `json:"fin"`
	Inicio time.Time `json:"inicio"`
}

// Problema Formato de error único de la API, según RFC 9457 (problem details). Se
// usa un estándar en vez de un formato propio para que el cliente pueda
// tratar los errores de forma uniforme y para que una respuesta de error
// sea indistinguible venga del componente de ARQ-01 que venga.
type Problema struct {
	// Detail Explicación concreta de esta ocurrencia.
	Detail *string `json:"detail,omitempty"`

	// Errores Detalle por campo, cuando el problema es de validación.
	Errores *[]struct {
		Campo   string `json:"campo"`
		Mensaje string `json:"mensaje"`
	} `json:"errores,omitempty"`

	// Instance Identificador de la petición, para cruzar con las trazas.
	Instance *string `json:"instance,omitempty"`

	// Status Código HTTP, repetido en el cuerpo.
	Status int `json:"status"`

	// Title Resumen legible, constante para un mismo type.
	Title string `json:"title"`

	// Type Identificador estable del tipo de problema.
	//
	// Examples: https://api.reservas/errores/horario-ocupado
	Type string `json:"type"`
}

// Reserva defines model for Reserva.
type Reserva struct {
	Contacto *Contacto `json:"contacto,omitempty"`
	CreadaEn time.Time `json:"creada_en"`

	// Estado Estados de RF-28.
	Estado EstadoReserva `json:"estado"`

	// ExpiraEn Solo mientras el estado es `pendiente`. Pasado ese instante el cupo
	// puede liberarse (RF-27).
	ExpiraEn *time.Time         `json:"expira_en,omitempty"`
	Id       openapi_types.UUID `json:"id"`

	// Periodo Intervalo semiabierto `[inicio, fin)`. El límite inferior entra, el
	// superior no.
	//
	// No es un detalle de estilo: con ambos límites cerrados, 10:00–11:00 y
	// 11:00–12:00 comparten un instante, el operador `&&` de PostgreSQL las
	// declara solapadas y la restricción EXCLUDE rechazaría dos citas
	// consecutivas perfectamente válidas.
	Periodo Periodo `json:"periodo"`

	// PrecioCobrado El monto va como cadena decimal, no como número. En JSON los números son
	// de coma flotante y 80000.10 no se representa exactamente; con dinero eso
	// acaba en un céntimo de diferencia entre lo que se cobra y lo que se
	// muestra. La columna del esquema es `numeric`, que sí es exacta, y una
	// cadena la preserva de extremo a extremo.
	PrecioCobrado Dinero             `json:"precio_cobrado"`
	RecursoId     openapi_types.UUID `json:"recurso_id"`
	ServicioId    openapi_types.UUID `json:"servicio_id"`
}

// ReservaCreada Lo que devuelve la ruta crítica: la reserva ya con el cupo garantizado,
// más el secreto que el cliente necesita para confirmar el pago contra
// Stripe directamente, sin que el importe pase por este backend.
type ReservaCreada struct {
	// PagoClientSecret `client_secret` del PaymentIntent de Stripe.
	PagoClientSecret *string `json:"pago_client_secret,omitempty"`
	Reserva          Reserva `json:"reserva"`
}

// Sede defines model for Sede.
type Sede struct {
	Direccion *string            `json:"direccion,omitempty"`
	Estado    EstadoCatalogo     `json:"estado"`
	Id        openapi_types.UUID `json:"id"`
	Nombre    string             `json:"nombre"`

	// ZonaHoraria Identificador IANA. Se guarda por sede y no global porque un tenant
	// puede operar en varias zonas (RF-38), y una franja horaria sin zona
	// es ambigua dos veces al año.
	//
	//
	// Examples: America/Bogota
	ZonaHoraria string `json:"zona_horaria"`
}

// Servicio defines model for Servicio.
type Servicio struct {
	Descripcion *string `json:"descripcion,omitempty"`

	// DuracionMin Duración en minutos.
	DuracionMin int                `json:"duracion_min"`
	Estado      EstadoCatalogo     `json:"estado"`
	Id          openapi_types.UUID `json:"id"`
	Nombre      string             `json:"nombre"`

	// Precio El monto va como cadena decimal, no como número. En JSON los números son
	// de coma flotante y 80000.10 no se representa exactamente; con dinero eso
	// acaba en un céntimo de diferencia entre lo que se cobra y lo que se
	// muestra. La columna del esquema es `numeric`, que sí es exacta, y una
	// cadena la preserva de extremo a extremo.
	Precio Dinero             `json:"precio"`
	SedeId openapi_types.UUID `json:"sede_id"`
}

// Tenant defines model for Tenant.
type Tenant = openapi_types.UUID

// DemasiadasPeticiones Formato de error único de la API, según RFC 9457 (problem details). Se
// usa un estándar en vez de un formato propio para que el cliente pueda
// tratar los errores de forma uniforme y para que una respuesta de error
// sea indistinguible venga del componente de ARQ-01 que venga.
type DemasiadasPeticiones = Problema

// ErrorInterno Formato de error único de la API, según RFC 9457 (problem details). Se
// usa un estándar en vez de un formato propio para que el cliente pueda
// tratar los errores de forma uniforme y para que una respuesta de error
// sea indistinguible venga del componente de ARQ-01 que venga.
type ErrorInterno = Problema

// NoEncontrado Formato de error único de la API, según RFC 9457 (problem details). Se
// usa un estándar en vez de un formato propio para que el cliente pueda
// tratar los errores de forma uniforme y para que una respuesta de error
// sea indistinguible venga del componente de ARQ-01 que venga.
type NoEncontrado = Problema

// NoProcesable Formato de error único de la API, según RFC 9457 (problem details). Se
// usa un estándar en vez de un formato propio para que el cliente pueda
// tratar los errores de forma uniforme y para que una respuesta de error
// sea indistinguible venga del componente de ARQ-01 que venga.
type NoProcesable = Problema

// PeticionInvalida Formato de error único de la API, según RFC 9457 (problem details). Se
// usa un estándar en vez de un formato propio para que el cliente pueda
// tratar los errores de forma uniforme y para que una respuesta de error
// sea indistinguible venga del componente de ARQ-01 que venga.
type PeticionInvalida = Problema

// ConsultarDisponibilidadParams defines parameters for ConsultarDisponibilidad.
type ConsultarDisponibilidadParams struct {
	ServicioId openapi_types.UUID `form:"servicio_id" json:"servicio_id"`

	// Desde Instante inicial, inclusive.
	Desde time.Time `form:"desde" json:"desde"`

	// Hasta Instante final, exclusive.
	Hasta time.Time `form:"hasta" json:"hasta"`

	// XTenantId Tenant sobre el que se opera. Provisional: en cuanto exista
	// autenticación (RF-12) el tenant se deriva del token y esta cabecera
	// desaparece. Aceptarla de un cliente en producción permitiría leer los
	// datos de cualquier otro tenant.
	XTenantId Tenant `json:"X-Tenant-Id"`
}

// ListarReservasParams defines parameters for ListarReservas.
type ListarReservasParams struct {
	Estado *[]EstadoReserva `form:"estado,omitempty" json:"estado,omitempty"`
	Desde  *time.Time       `form:"desde,omitempty" json:"desde,omitempty"`
	Hasta  *time.Time       `form:"hasta,omitempty" json:"hasta,omitempty"`
	Limite *int             `form:"limite,omitempty" json:"limite,omitempty"`

	// Cursor Cursor opaco de la página siguiente. Paginación por cursor y no por
	// desplazamiento: con OFFSET, insertar una fila mientras se pagina
	// desplaza el resto y el cliente ve duplicados o se salta filas.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// XTenantId Tenant sobre el que se opera. Provisional: en cuanto exista
	// autenticación (RF-12) el tenant se deriva del token y esta cabecera
	// desaparece. Aceptarla de un cliente en producción permitiría leer los
	// datos de cualquier otro tenant.
	XTenantId Tenant `json:"X-Tenant-Id"`
}

// CrearReservaParams defines parameters for CrearReserva.
type CrearReservaParams struct {
	// XTenantId Tenant sobre el que se opera. Provisional: en cuanto exista
	// autenticación (RF-12) el tenant se deriva del token y esta cabecera
	// desaparece. Aceptarla de un cliente en producción permitiría leer los
	// datos de cualquier otro tenant.
	XTenantId Tenant `json:"X-Tenant-Id"`

	// IdempotencyKey Clave única de la operación. Obligatoria, no opcional: un agente que
	// reintenta un POST tras un timeout crearía dos bloqueos que nadie
	// libera hasta el TTL. Repetir la misma clave devuelve la reserva ya
	// creada en vez de crear otra.
	IdempotencyKey string `json:"Idempotency-Key"`
}

// ObtenerReservaParams defines parameters for ObtenerReserva.
type ObtenerReservaParams struct {
	// XTenantId Tenant sobre el que se opera. Provisional: en cuanto exista
	// autenticación (RF-12) el tenant se deriva del token y esta cabecera
	// desaparece. Aceptarla de un cliente en producción permitiría leer los
	// datos de cualquier otro tenant.
	XTenantId Tenant `json:"X-Tenant-Id"`
}

// ListarSedesParams defines parameters for ListarSedes.
type ListarSedesParams struct {
	// XTenantId Tenant sobre el que se opera. Provisional: en cuanto exista
	// autenticación (RF-12) el tenant se deriva del token y esta cabecera
	// desaparece. Aceptarla de un cliente en producción permitiría leer los
	// datos de cualquier otro tenant.
	XTenantId Tenant `json:"X-Tenant-Id"`
}

// ListarServiciosParams defines parameters for ListarServicios.
type ListarServiciosParams struct {
	SedeId *openapi_types.UUID `form:"sede_id,omitempty" json:"sede_id,omitempty"`

	// XTenantId Tenant sobre el que se opera. Provisional: en cuanto exista
	// autenticación (RF-12) el tenant se deriva del token y esta cabecera
	// desaparece. Aceptarla de un cliente en producción permitiría leer los
	// datos de cualquier otro tenant.
	XTenantId Tenant `json:"X-Tenant-Id"`
}

// CrearReservaJSONRequestBody defines body for CrearReserva for application/json ContentType.
type CrearReservaJSONRequestBody = NuevaReserva

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ConsultarDisponibilidad Franjas libres de un servicio en un rango
	// (GET /v1/disponibilidad)
	ConsultarDisponibilidad(w http.ResponseWriter, r *http.Request, params ConsultarDisponibilidadParams)
	// ListarReservas Reservas de la cuenta (RF-02, filtros de RF-09)
	// (GET /v1/reservas)
	ListarReservas(w http.ResponseWriter, r *http.Request, params ListarReservasParams)
	// CrearReserva Crear una reserva (RF-01)
	// (POST /v1/reservas)
	CrearReserva(w http.ResponseWriter, r *http.Request, params CrearReservaParams)
	// ObtenerReserva Detalle de una reserva (RF-03)
	// (GET /v1/reservas/{id})
	ObtenerReserva(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, params ObtenerReservaParams)
	// ListarSedes Sedes del tenant
	// (GET /v1/sedes)
	ListarSedes(w http.ResponseWriter, r *http.Request, params ListarSedesParams)
	// ListarServicios Servicios ofrecidos, opcionalmente filtrados por sede
	// (GET /v1/servicios)
	ListarServicios(w http.ResponseWriter, r *http.Request, params ListarServiciosParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ConsultarDisponibilidad operation middleware
func (siw *ServerInterfaceWrapper) ConsultarDisponibilidad(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ConsultarDisponibilidadParams

	// ------------- Required query parameter "servicio_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "servicio_id", r.URL.Query(), &params.ServicioId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "servicio_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "servicio_id", Err: err})
		}
		return
	}

	// ------------- Required query parameter "desde" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "desde", r.URL.Query(), &params.Desde, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "desde"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "desde", Err: err})
		}
		return
	}

	// ------------- Required query parameter "hasta" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "hasta", r.URL.Query(), &params.Hasta, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "hasta"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hasta", Err: err})
		}
		return
	}

	headers := r.Header

	// ------------- Required header parameter "X-Tenant-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tenant-Id")]; found {
		var XTenantId Tenant
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Tenant-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tenant-Id", valueList[0], &XTenantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Tenant-Id", Err: err})
			return
		}

		params.XTenantId = XTenantId

	} else {
		err := fmt.Errorf("Header parameter X-Tenant-Id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Tenant-Id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ConsultarDisponibilidad(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListarReservas operation middleware
func (siw *ServerInterfaceWrapper) ListarReservas(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListarReservasParams

	// ------------- Optional query parameter "estado" -------------

	err = runtime.BindQueryParameterWithOptions("form", false, false, "estado", r.URL.Query(), &params.Estado, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "estado"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "estado", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "desde" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "desde", r.URL.Query(), &params.Desde, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "desde"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "desde", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "hasta" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "hasta", r.URL.Query(), &params.Hasta, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "hasta"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hasta", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limite" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limite", r.URL.Query(), &params.Limite, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limite"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limite", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	headers := r.Header

	// ------------- Required header parameter "X-Tenant-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tenant-Id")]; found {
		var XTenantId Tenant
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Tenant-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tenant-Id", valueList[0], &XTenantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Tenant-Id", Err: err})
			return
		}

		params.XTenantId = XTenantId

	} else {
		err := fmt.Errorf("Header parameter X-Tenant-Id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Tenant-Id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListarReservas(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CrearReserva operation middleware
func (siw *ServerInterfaceWrapper) CrearReserva(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CrearReservaParams

	headers := r.Header

	// ------------- Required header parameter "X-Tenant-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tenant-Id")]; found {
		var XTenantId Tenant
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Tenant-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tenant-Id", valueList[0], &XTenantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Tenant-Id", Err: err})
			return
		}

		params.XTenantId = XTenantId

	} else {
		err := fmt.Errorf("Header parameter X-Tenant-Id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Tenant-Id", Err: err})
		return
	}

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CrearReserva(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ObtenerReserva operation middleware
func (siw *ServerInterfaceWrapper) ObtenerReserva(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ObtenerReservaParams

	headers := r.Header

	// ------------- Required header parameter "X-Tenant-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tenant-Id")]; found {
		var XTenantId Tenant
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Tenant-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tenant-Id", valueList[0], &XTenantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Tenant-Id", Err: err})
			return
		}

		params.XTenantId = XTenantId

	} else {
		err := fmt.Errorf("Header parameter X-Tenant-Id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Tenant-Id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ObtenerReserva(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListarSedes operation middleware
func (siw *ServerInterfaceWrapper) ListarSedes(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListarSedesParams

	headers := r.Header

	// ------------- Required header parameter "X-Tenant-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tenant-Id")]; found {
		var XTenantId Tenant
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Tenant-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tenant-Id", valueList[0], &XTenantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Tenant-Id", Err: err})
			return
		}

		params.XTenantId = XTenantId

	} else {
		err := fmt.Errorf("Header parameter X-Tenant-Id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Tenant-Id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListarSedes(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListarServicios operation middleware
func (siw *ServerInterfaceWrapper) ListarServicios(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListarServiciosParams

	// ------------- Optional query parameter "sede_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sede_id", r.URL.Query(), &params.SedeId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "sede_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sede_id", Err: err})
		}
		return
	}

	headers := r.Header

	// ------------- Required header parameter "X-Tenant-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Tenant-Id")]; found {
		var XTenantId Tenant
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Tenant-Id", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Tenant-Id", valueList[0], &XTenantId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Tenant-Id", Err: err})
			return
		}

		params.XTenantId = XTenantId

	} else {
		err := fmt.Errorf("Header parameter X-Tenant-Id is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "X-Tenant-Id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListarServicios(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/sedes", wrapper.ListarSedes)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/servicios", wrapper.ListarServicios)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/disponibilidad", wrapper.ConsultarDisponibilidad)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/reservas", wrapper.ListarReservas)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/reservas", wrapper.CrearReserva)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/v1/reservas/{id}", wrapper.ObtenerReserva)

	return m
}

type DemasiadasPeticionesResponseHeaders struct {
	RetryAfter *int
}
type DemasiadasPeticionesApplicationProblemPlusJSONResponse struct {
	Body Problema

	Headers DemasiadasPeticionesResponseHeaders
}

type ErrorInternoApplicationProblemPlusJSONResponse Problema

type NoEncontradoApplicationProblemPlusJSONResponse Problema

type NoProcesableApplicationProblemPlusJSONResponse Problema

type PeticionInvalidaApplicationProblemPlusJSONResponse Problema

type ConsultarDisponibilidadRequestObject struct {
	Params ConsultarDisponibilidadParams
}

type ConsultarDisponibilidadResponseObject interface {
	VisitConsultarDisponibilidadResponse(w http.ResponseWriter) error
}

type ConsultarDisponibilidad200JSONResponse Disponibilidad

func (response ConsultarDisponibilidad200JSONResponse) VisitConsultarDisponibilidadResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ConsultarDisponibilidad400ApplicationProblemPlusJSONResponse struct {
	PeticionInvalidaApplicationProblemPlusJSONResponse
}

func (response ConsultarDisponibilidad400ApplicationProblemPlusJSONResponse) VisitConsultarDisponibilidadResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ConsultarDisponibilidad404ApplicationProblemPlusJSONResponse struct {
	NoEncontradoApplicationProblemPlusJSONResponse
}

func (response ConsultarDisponibilidad404ApplicationProblemPlusJSONResponse) VisitConsultarDisponibilidadResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ConsultarDisponibilidad500ApplicationProblemPlusJSONResponse struct {
	ErrorInternoApplicationProblemPlusJSONResponse
}

func (response ConsultarDisponibilidad500ApplicationProblemPlusJSONResponse) VisitConsultarDisponibilidadResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListarReservasRequestObject struct {
	Params ListarReservasParams
}

type ListarReservasResponseObject interface {
	VisitListarReservasResponse(w http.ResponseWriter) error
}

type ListarReservas200JSONResponse ListaReservas

func (response ListarReservas200JSONResponse) VisitListarReservasResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListarReservas400ApplicationProblemPlusJSONResponse struct {
	PeticionInvalidaApplicationProblemPlusJSONResponse
}

func (response ListarReservas400ApplicationProblemPlusJSONResponse) VisitListarReservasResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListarReservas500ApplicationProblemPlusJSONResponse struct {
	ErrorInternoApplicationProblemPlusJSONResponse
}

func (response ListarReservas500ApplicationProblemPlusJSONResponse) VisitListarReservasResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CrearReservaRequestObject struct {
	Params CrearReservaParams
	Body   *CrearReservaJSONRequestBody
}

type CrearReservaResponseObject interface {
	VisitCrearReservaResponse(w http.ResponseWriter) error
}

type CrearReserva201JSONResponse ReservaCreada

func (response CrearReserva201JSONResponse) VisitCrearReservaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CrearReserva400ApplicationProblemPlusJSONResponse struct {
	PeticionInvalidaApplicationProblemPlusJSONResponse
}

func (response CrearReserva400ApplicationProblemPlusJSONResponse) VisitCrearReservaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CrearReserva404ApplicationProblemPlusJSONResponse struct {
	NoEncontradoApplicationProblemPlusJSONResponse
}

func (response CrearReserva404ApplicationProblemPlusJSONResponse) VisitCrearReservaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CrearReserva409ApplicationProblemPlusJSONResponse Problema

func (response CrearReserva409ApplicationProblemPlusJSONResponse) VisitCrearReservaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CrearReserva422ApplicationProblemPlusJSONResponse struct {
	NoProcesableApplicationProblemPlusJSONResponse
}

func (response CrearReserva422ApplicationProblemPlusJSONResponse) VisitCrearReservaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type CrearReserva429ApplicationProblemPlusJSONResponse struct {
	DemasiadasPeticionesApplicationProblemPlusJSONResponse
}

func (response CrearReserva429ApplicationProblemPlusJSONResponse) VisitCrearReservaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type CrearReserva500ApplicationProblemPlusJSONResponse struct {
	ErrorInternoApplicationProblemPlusJSONResponse
}

func (response CrearReserva500ApplicationProblemPlusJSONResponse) VisitCrearReservaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ObtenerReservaRequestObject struct {
	Id     openapi_types.UUID `json:"id"`
	Params ObtenerReservaParams
}

type ObtenerReservaResponseObject interface {
	VisitObtenerReservaResponse(w http.ResponseWriter) error
}

type ObtenerReserva200JSONResponse Reserva

func (response ObtenerReserva200JSONResponse) VisitObtenerReservaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ObtenerReserva404ApplicationProblemPlusJSONResponse struct {
	NoEncontradoApplicationProblemPlusJSONResponse
}

func (response ObtenerReserva404ApplicationProblemPlusJSONResponse) VisitObtenerReservaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ObtenerReserva500ApplicationProblemPlusJSONResponse struct {
	ErrorInternoApplicationProblemPlusJSONResponse
}

func (response ObtenerReserva500ApplicationProblemPlusJSONResponse) VisitObtenerReservaResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListarSedesRequestObject struct {
	Params ListarSedesParams
}

type ListarSedesResponseObject interface {
	VisitListarSedesResponse(w http.ResponseWriter) error
}

type ListarSedes200JSONResponse ListaSedes

func (response ListarSedes200JSONResponse) VisitListarSedesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListarSedes400ApplicationProblemPlusJSONResponse struct {
	PeticionInvalidaApplicationProblemPlusJSONResponse
}

func (response ListarSedes400ApplicationProblemPlusJSONResponse) VisitListarSedesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListarSedes500ApplicationProblemPlusJSONResponse struct {
	ErrorInternoApplicationProblemPlusJSONResponse
}

func (response ListarSedes500ApplicationProblemPlusJSONResponse) VisitListarSedesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListarServiciosRequestObject struct {
	Params ListarServiciosParams
}

type ListarServiciosResponseObject interface {
	VisitListarServiciosResponse(w http.ResponseWriter) error
}

type ListarServicios200JSONResponse ListaServicios

func (response ListarServicios200JSONResponse) VisitListarServiciosResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListarServicios400ApplicationProblemPlusJSONResponse struct {
	PeticionInvalidaApplicationProblemPlusJSONResponse
}

func (response ListarServicios400ApplicationProblemPlusJSONResponse) VisitListarServiciosResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListarServicios500ApplicationProblemPlusJSONResponse struct {
	ErrorInternoApplicationProblemPlusJSONResponse
}

func (response ListarServicios500ApplicationProblemPlusJSONResponse) VisitListarServiciosResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ConsultarDisponibilidad Franjas libres de un servicio en un rango
	// (GET /v1/disponibilidad)
	ConsultarDisponibilidad(ctx context.Context, request ConsultarDisponibilidadRequestObject) (ConsultarDisponibilidadResponseObject, error)
	// ListarReservas Reservas de la cuenta (RF-02, filtros de RF-09)
	// (GET /v1/reservas)
	ListarReservas(ctx context.Context, request ListarReservasRequestObject) (ListarReservasResponseObject, error)
	// CrearReserva Crear una reserva (RF-01)
	// (POST /v1/reservas)
	CrearReserva(ctx context.Context, request CrearReservaRequestObject) (CrearReservaResponseObject, error)
	// ObtenerReserva Detalle de una reserva (RF-03)
	// (GET /v1/reservas/{id})
	ObtenerReserva(ctx context.Context, request ObtenerReservaRequestObject) (ObtenerReservaResponseObject, error)
	// ListarSedes Sedes del tenant
	// (GET /v1/sedes)
	ListarSedes(ctx context.Context, request ListarSedesRequestObject) (ListarSedesResponseObject, error)
	// ListarServicios Servicios ofrecidos, opcionalmente filtrados por sede
	// (GET /v1/servicios)
	ListarServicios(ctx context.Context, request ListarServiciosRequestObject) (ListarServiciosResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ConsultarDisponibilidad operation middleware
func (sh *strictHandler) ConsultarDisponibilidad(w http.ResponseWriter, r *http.Request, params ConsultarDisponibilidadParams) {
	var request ConsultarDisponibilidadRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ConsultarDisponibilidad(ctx, request.(ConsultarDisponibilidadRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ConsultarDisponibilidad")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ConsultarDisponibilidadResponseObject); ok {
		if err := validResponse.VisitConsultarDisponibilidadResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListarReservas operation middleware
func (sh *strictHandler) ListarReservas(w http.ResponseWriter, r *http.Request, params ListarReservasParams) {
	var request ListarReservasRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListarReservas(ctx, request.(ListarReservasRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListarReservas")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListarReservasResponseObject); ok {
		if err := validResponse.VisitListarReservasResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CrearReserva operation middleware
func (sh *strictHandler) CrearReserva(w http.ResponseWriter, r *http.Request, params CrearReservaParams) {
	var request CrearReservaRequestObject

	request.Params = params

	var body CrearReservaJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CrearReserva(ctx, request.(CrearReservaRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CrearReserva")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CrearReservaResponseObject); ok {
		if err := validResponse.VisitCrearReservaResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ObtenerReserva operation middleware
func (sh *strictHandler) ObtenerReserva(w http.ResponseWriter, r *http.Request, id openapi_types.UUID, params ObtenerReservaParams) {
	var request ObtenerReservaRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ObtenerReserva(ctx, request.(ObtenerReservaRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ObtenerReserva")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ObtenerReservaResponseObject); ok {
		if err := validResponse.VisitObtenerReservaResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListarSedes operation middleware
func (sh *strictHandler) ListarSedes(w http.ResponseWriter, r *http.Request, params ListarSedesParams) {
	var request ListarSedesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListarSedes(ctx, request.(ListarSedesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListarSedes")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListarSedesResponseObject); ok {
		if err := validResponse.VisitListarSedesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListarServicios operation middleware
func (sh *strictHandler) ListarServicios(w http.ResponseWriter, r *http.Request, params ListarServiciosParams) {
	var request ListarServiciosRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListarServicios(ctx, request.(ListarServiciosRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListarServicios")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListarServiciosResponseObject); ok {
		if err := validResponse.VisitListarServiciosResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
