/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/sedes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sedes del tenant */
        get: operations["listarSedes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/servicios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Servicios ofrecidos, opcionalmente filtrados por sede */
        get: operations["listarServicios"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/disponibilidad": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Franjas libres de un servicio en un rango
         * @description Sirve el 90% del tráfico (RNF-03) desde caché, con los 2 s de
         *     desactualización que RNF-10 autoriza.
         *
         *     La lectura es optimista a propósito: puede devolver una franja que otro
         *     cliente acaba de tomar. Quien decide es el núcleo al insertar, contra la
         *     restricción EXCLUDE (flujo alternativo 3 de RF-01). Un cliente que trate
         *     esta respuesta como una reserva garantizada está mal escrito.
         */
        get: operations["consultarDisponibilidad"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reservas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reservas de la cuenta (RF-02, filtros de RF-09) */
        get: operations["listarReservas"];
        put?: never;
        /**
         * Crear una reserva (RF-01)
         * @description Ruta crítica de RNF-01: presupuesto de 200 ms. Devuelve una reserva
         *     **pendiente** con el cupo ya garantizado, sin esperar a que el pago se
         *     confirme. La confirmación llega después por el webhook de Stripe (RF-33),
         *     fuera de este presupuesto.
         *
         *     La reserva pendiente caduca en `expira_en`. Si el pago no llega antes, un
         *     trabajador la marca expirada y libera el cupo (RF-27).
         */
        post: operations["crearReserva"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reservas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de una reserva (RF-03) */
        get: operations["obtenerReserva"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        EstadoCatalogo: "activo" | "inactivo";
        Sede: {
            /** Format: uuid */
            id: string;
            nombre: string;
            /**
             * @description Identificador IANA. Se guarda por sede y no global porque un tenant
             *     puede operar en varias zonas (RF-38), y una franja horaria sin zona es
             *     ambigua dos veces al año.
             * @example America/Bogota
             */
            zona_horaria: string;
            direccion?: string;
            estado: components["schemas"]["EstadoCatalogo"];
        };
        ListaSedes: {
            datos: components["schemas"]["Sede"][];
        };
        /**
         * @description Formato de error único de la API, según RFC 9457 (problem details). Se usa
         *     un estándar en vez de un formato propio para que el cliente pueda tratar los
         *     errores de forma uniforme y para que una respuesta de error sea
         *     indistinguible venga del componente de ARQ-01 que venga.
         */
        Problema: {
            /**
             * Format: uri
             * @description Identificador estable del tipo de problema.
             * @example https://api.reservas/errores/horario-ocupado
             */
            type: string;
            /** @description Resumen legible, constante para un mismo type. */
            title: string;
            /** @description Código HTTP, repetido en el cuerpo. */
            status: number;
            /** @description Explicación concreta de esta ocurrencia. */
            detail?: string;
            /** @description Identificador de la petición, para cruzar con las trazas. */
            instance?: string;
            /** @description Detalle por campo, cuando el problema es de validación. */
            errores?: {
                campo: string;
                mensaje: string;
            }[];
        };
        /**
         * @description El monto va como cadena decimal, no como número. En JSON los números son de
         *     coma flotante y 80000.10 no se representa exactamente; con dinero eso acaba
         *     en un céntimo de diferencia entre lo que se cobra y lo que se muestra. La
         *     columna del esquema es `numeric`, que sí es exacta, y una cadena la preserva
         *     de extremo a extremo.
         */
        Dinero: {
            /** @example 80000.00 */
            monto: string;
            /**
             * @description Código ISO 4217.
             * @example COP
             */
            moneda: string;
        };
        Servicio: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            sede_id: string;
            nombre: string;
            descripcion?: string;
            /** @description Duración en minutos. */
            duracion_min: number;
            precio: components["schemas"]["Dinero"];
            estado: components["schemas"]["EstadoCatalogo"];
        };
        ListaServicios: {
            datos: components["schemas"]["Servicio"][];
        };
        /**
         * @description Intervalo semiabierto `[inicio, fin)`. El límite inferior entra, el superior
         *     no.
         *
         *     No es un detalle de estilo: con ambos límites cerrados, 10:00–11:00 y
         *     11:00–12:00 comparten un instante, el operador `&&` de PostgreSQL las declara
         *     solapadas y la restricción EXCLUDE rechazaría dos citas consecutivas
         *     perfectamente válidas.
         */
        Periodo: {
            /** Format: date-time */
            inicio: string;
            /** Format: date-time */
            fin: string;
        };
        Franja: {
            periodo: components["schemas"]["Periodo"];
            /** Format: uuid */
            recurso_id: string;
        };
        Disponibilidad: {
            /** Format: uuid */
            servicio_id: string;
            franjas: components["schemas"]["Franja"][];
            /**
             * Format: date-time
             * @description Cuándo se calculó esta vista. El cliente puede saber así cuánta
             *     desactualización está viendo, dentro de los 2 s que RNF-10 permite.
             */
            calculada_en: string;
        };
        /**
         * @description Estados de RF-28.
         * @enum {string}
         */
        EstadoReserva: "pendiente" | "confirmada" | "en_curso" | "completada" | "cancelada" | "no_show" | "expirada";
        Contacto: {
            nombre: string;
            /** Format: email */
            email: string;
            telefono?: string;
        };
        Reserva: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            servicio_id: string;
            /** Format: uuid */
            recurso_id: string;
            periodo: components["schemas"]["Periodo"];
            estado: components["schemas"]["EstadoReserva"];
            precio_cobrado: components["schemas"]["Dinero"];
            contacto?: components["schemas"]["Contacto"];
            /**
             * Format: date-time
             * @description Solo mientras el estado es `pendiente`. Pasado ese instante el cupo
             *     puede liberarse (RF-27).
             */
            expira_en?: string;
            /** Format: date-time */
            creada_en: string;
        };
        ListaReservas: {
            datos: components["schemas"]["Reserva"][];
            /** @description Ausente cuando no hay más páginas. */
            siguiente_cursor?: string;
        };
        NuevaReserva: {
            /** Format: uuid */
            servicio_id: string;
            /** Format: uuid */
            recurso_id: string;
            periodo: components["schemas"]["Periodo"];
            contacto: components["schemas"]["Contacto"];
            /** @description Código de descuento, si aplica (RF-08). */
            voucher_codigo?: string;
        };
        /**
         * @description Lo que devuelve la ruta crítica: la reserva ya con el cupo garantizado, más
         *     el secreto que el cliente necesita para confirmar el pago contra Stripe
         *     directamente, sin que el importe pase por este backend.
         */
        ReservaCreada: {
            reserva: components["schemas"]["Reserva"];
            /** @description `client_secret` del PaymentIntent de Stripe. */
            pago_client_secret?: string;
        };
    };
    responses: {
        /** @description La petición está mal formada */
        PeticionInvalida: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problema"];
            };
        };
        /** @description Error no previsto */
        ErrorInterno: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problema"];
            };
        };
        /**
         * @description No existe. Bajo RLS, "no existe" y "existe pero es de otro tenant" son
         *     indistinguibles, y así debe ser: distinguirlos filtraría la existencia de
         *     datos ajenos.
         */
        NoEncontrado: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problema"];
            };
        };
        /** @description Sintácticamente válida pero viola una regla de negocio */
        NoProcesable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problema"];
            };
        };
        /** @description Se superó la cuota de la cuenta o del agente (RNF-08) */
        DemasiadasPeticiones: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problema"];
            };
        };
    };
    parameters: {
        /**
         * @description Tenant sobre el que se opera. Provisional: en cuanto exista autenticación
         *     (RF-12) el tenant se deriva del token y esta cabecera desaparece. Aceptarla
         *     de un cliente en producción permitiría leer los datos de cualquier otro
         *     tenant.
         */
        Tenant: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listarSedes: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Tenant sobre el que se opera. Provisional: en cuanto exista autenticación
                 *     (RF-12) el tenant se deriva del token y esta cabecera desaparece. Aceptarla
                 *     de un cliente en producción permitiría leer los datos de cualquier otro
                 *     tenant.
                 */
                "X-Tenant-Id": components["parameters"]["Tenant"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado de sedes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListaSedes"];
                };
            };
            400: components["responses"]["PeticionInvalida"];
            500: components["responses"]["ErrorInterno"];
        };
    };
    listarServicios: {
        parameters: {
            query?: {
                sede_id?: string;
            };
            header: {
                /**
                 * @description Tenant sobre el que se opera. Provisional: en cuanto exista autenticación
                 *     (RF-12) el tenant se deriva del token y esta cabecera desaparece. Aceptarla
                 *     de un cliente en producción permitiría leer los datos de cualquier otro
                 *     tenant.
                 */
                "X-Tenant-Id": components["parameters"]["Tenant"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado de servicios */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListaServicios"];
                };
            };
            400: components["responses"]["PeticionInvalida"];
            500: components["responses"]["ErrorInterno"];
        };
    };
    consultarDisponibilidad: {
        parameters: {
            query: {
                servicio_id: string;
                /** @description Instante inicial, inclusive. */
                desde: string;
                /** @description Instante final, exclusive. */
                hasta: string;
            };
            header: {
                /**
                 * @description Tenant sobre el que se opera. Provisional: en cuanto exista autenticación
                 *     (RF-12) el tenant se deriva del token y esta cabecera desaparece. Aceptarla
                 *     de un cliente en producción permitiría leer los datos de cualquier otro
                 *     tenant.
                 */
                "X-Tenant-Id": components["parameters"]["Tenant"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Franjas libres */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Disponibilidad"];
                };
            };
            400: components["responses"]["PeticionInvalida"];
            404: components["responses"]["NoEncontrado"];
            500: components["responses"]["ErrorInterno"];
        };
    };
    listarReservas: {
        parameters: {
            query?: {
                estado?: components["schemas"]["EstadoReserva"][];
                desde?: string;
                hasta?: string;
                limite?: number;
                /**
                 * @description Cursor opaco de la página siguiente. Paginación por cursor y no por
                 *     desplazamiento: con OFFSET, insertar una fila mientras se pagina
                 *     desplaza el resto y el cliente ve duplicados o se salta filas.
                 */
                cursor?: string;
            };
            header: {
                /**
                 * @description Tenant sobre el que se opera. Provisional: en cuanto exista autenticación
                 *     (RF-12) el tenant se deriva del token y esta cabecera desaparece. Aceptarla
                 *     de un cliente en producción permitiría leer los datos de cualquier otro
                 *     tenant.
                 */
                "X-Tenant-Id": components["parameters"]["Tenant"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de reservas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListaReservas"];
                };
            };
            400: components["responses"]["PeticionInvalida"];
            500: components["responses"]["ErrorInterno"];
        };
    };
    crearReserva: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Tenant sobre el que se opera. Provisional: en cuanto exista autenticación
                 *     (RF-12) el tenant se deriva del token y esta cabecera desaparece. Aceptarla
                 *     de un cliente en producción permitiría leer los datos de cualquier otro
                 *     tenant.
                 */
                "X-Tenant-Id": components["parameters"]["Tenant"];
                /**
                 * @description Clave única de la operación. Obligatoria, no opcional: un agente que
                 *     reintenta un POST tras un timeout crearía dos bloqueos que nadie
                 *     libera hasta el TTL. Repetir la misma clave devuelve la reserva ya
                 *     creada en vez de crear otra.
                 */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NuevaReserva"];
            };
        };
        responses: {
            /** @description Reserva creada, pendiente de pago */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservaCreada"];
                };
            };
            400: components["responses"]["PeticionInvalida"];
            404: components["responses"]["NoEncontrado"];
            /**
             * @description El horario ya está tomado. Es la respuesta al rechazo de la
             *     restricción EXCLUDE por otra transacción concurrente: no es un error
             *     del cliente ni del servidor, es el resultado normal de perder una
             *     carrera por el mismo cupo.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
            422: components["responses"]["NoProcesable"];
            429: components["responses"]["DemasiadasPeticiones"];
            500: components["responses"]["ErrorInterno"];
        };
    };
    obtenerReserva: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Tenant sobre el que se opera. Provisional: en cuanto exista autenticación
                 *     (RF-12) el tenant se deriva del token y esta cabecera desaparece. Aceptarla
                 *     de un cliente en producción permitiría leer los datos de cualquier otro
                 *     tenant.
                 */
                "X-Tenant-Id": components["parameters"]["Tenant"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description La reserva */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reserva"];
                };
            };
            404: components["responses"]["NoEncontrado"];
            500: components["responses"]["ErrorInterno"];
        };
    };
}
