/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/sedes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sedes del tenant */
        get: operations["listarSedes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/servicios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Servicios ofrecidos, opcionalmente filtrados por sede */
        get: operations["listarServicios"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/disponibilidad": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Franjas libres de un servicio en un rango
         * @description Sirve el 90% del tráfico (RNF-03) desde caché, con los 2 s de
         *     desactualización que RNF-10 autoriza.
         *
         *     La lectura es optimista a propósito: puede devolver una franja que otro
         *     cliente acaba de tomar. Quien decide es el núcleo al insertar, contra la
         *     restricción EXCLUDE (flujo alternativo 3 de RF-01). Un cliente que trate
         *     esta respuesta como una reserva garantizada está mal escrito.
         */
        get: operations["consultarDisponibilidad"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sesiones/codigo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pedir un código para ver las reservas propias
         * @description Manda un código de seis dígitos al correo indicado (RF-02, con los
         *     parámetros de RF-19: seis dígitos, vigencia corta, un solo uso).
         *
         *     **Responde igual exista o no ese correo** (RF-12 A12). Distinguirlos
         *     permitiría enumerar quién ha reservado en el negocio probando direcciones.
         *
         *     Pedir un código nuevo invalida el anterior del mismo destino: tres códigos
         *     vivos a la vez triplicarían lo que puede adivinar quien los esté probando.
         */
        post: operations["solicitarCodigo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sesiones/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Canjear el código por un token de acceso */
        post: operations["canjearCodigo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reservas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reservas de quien pide (RF-02, filtros de RF-09)
         * @description El alcance NO es fijo: sale de quién presenta el token (RF-23). Hoy solo
         *     existe el token de invitado, así que devuelve las reservas hechas con el
         *     correo que ese token acredita.
         *
         *     Cuando exista RF-12, la misma ruta devolverá las de la cuenta a un
         *     `usuario` y las del tenant a un `administrador` (RF-32). Es una operación
         *     con el alcance acotado por la cuenta, no tres rutas distintas por rol.
         */
        get: operations["listarReservas"];
        put?: never;
        /**
         * Crear una reserva (RF-01)
         * @description Ruta crítica de RNF-01: presupuesto de 200 ms. Devuelve una reserva
         *     **pendiente** con el cupo ya garantizado, sin esperar a que el pago se
         *     confirme. La confirmación llega después por el webhook de Stripe (RF-33),
         *     fuera de este presupuesto.
         *
         *     La reserva pendiente caduca en `expira_en`. Si el pago no llega antes, un
         *     trabajador la marca expirada y libera el cupo (RF-27).
         */
        post: operations["crearReserva"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reservas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detalle de una reserva (RF-03)
         * @description Una reserva que existe pero es de otra persona responde `404`, no `403`.
         *     Un 403 confirmaría que esa reserva existe, y con identificadores ajenos
         *     eso permite comprobar cuáles son reales.
         */
        get: operations["obtenerReserva"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reservas/{id}/cancelacion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancelar una reserva (RF-06)
         * @description Aplica la política que la reserva congeló al crearse, no la vigente hoy
         *     (RF-15). Es lo que impide que un negocio endurezca su política el martes y
         *     se la aplique a quien reservó el lunes bajo otras condiciones.
         *
         *     Fuera del plazo de cancelación responde `422` con lo que faltaba, no un
         *     `403`: no es una cuestión de permisos, es que la regla del negocio no lo
         *     permite en ese momento.
         *
         *     El reembolso NO ocurre aquí. Se dispara aparte (RF-29) y por eso la
         *     respuesta no dice nada del dinero: prometerlo en esta respuesta sería
         *     afirmar algo que este componente no puede garantizar.
         */
        post: operations["cancelarReserva"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reservas/{id}/comprobante": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Comprobante de pago de una reserva (RF-34)
         * @description Esta SÍ exige identificación, a diferencia de las dos anteriores. Un
         *     comprobante lleva nombre, correo e importe: es el documento con más datos
         *     personales de todo el flujo, y no se entrega por conocer un identificador.
         *
         *     Una reserva ajena responde `404`, igual que una inexistente.
         */
        get: operations["obtenerComprobante"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pagos/intencion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preparar el cobro de una reserva pendiente (RF-01)
         * @description Devuelve el `client_secret` con el que el navegador confirma el pago
         *     directamente contra Stripe. El número de la tarjeta no pasa por este
         *     backend en ningún momento (RNF-05).
         *
         *     Es idempotente por construcción: llamarla dos veces sobre la misma reserva
         *     devuelve la misma intención, porque el motor solo admite un pago
         *     `iniciado` por reserva.
         *
         *     **Está fuera del presupuesto de RNF-01.** Crear un PaymentIntent es una
         *     llamada a Stripe, y por eso no ocurre dentro de `POST /v1/reservas`: la
         *     transacción que sostiene la invariante de RNF-10 no puede esperar a un
         *     tercero. Es la misma regla por la que ARQ-01 saca el pago del núcleo.
         */
        post: operations["crearIntencionPago"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pagos/{reserva_id}/estado": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Si la confirmación asíncrona ya llegó (RF-33)
         * @description Para consultar después de que Stripe.js diga "succeeded" en el navegador.
         *     Ese "succeeded" es de Stripe, no de este sistema: la reserva pasa a
         *     `confirmada` cuando el webhook llega, y eso ocurre unos cientos de
         *     milisegundos más tarde.
         *
         *     La interfaz consulta esta ruta hasta que el estado cambie, con un límite:
         *     si el webhook se retrasa mucho, el conciliador de RF-33 acaba
         *     preguntándole a Stripe por su cuenta, así que insistir aquí no acelera
         *     nada.
         */
        get: operations["consultarConfirmacion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        EstadoCatalogo: "activo" | "inactivo";
        Sede: {
            /** Format: uuid */
            id: string;
            nombre: string;
            /**
             * @description Identificador IANA. Se guarda por sede y no global porque un tenant
             *     puede operar en varias zonas (RF-38), y una franja horaria sin zona es
             *     ambigua dos veces al año.
             * @example America/Bogota
             */
            zona_horaria: string;
            direccion?: string;
            estado: components["schemas"]["EstadoCatalogo"];
        };
        ListaSedes: {
            datos: components["schemas"]["Sede"][];
        };
        /**
         * @description Formato de error único de la API, según RFC 9457 (problem details). Se usa
         *     un estándar en vez de un formato propio para que el cliente pueda tratar los
         *     errores de forma uniforme y para que una respuesta de error sea
         *     indistinguible venga del componente de ARQ-01 que venga.
         */
        Problema: {
            /**
             * Format: uri
             * @description Identificador estable del tipo de problema.
             * @example https://api.reservas/errores/horario-ocupado
             */
            type: string;
            /** @description Resumen legible, constante para un mismo type. */
            title: string;
            /** @description Código HTTP, repetido en el cuerpo. */
            status: number;
            /** @description Explicación concreta de esta ocurrencia. */
            detail?: string;
            /** @description Identificador de la petición, para cruzar con las trazas. */
            instance?: string;
            /** @description Detalle por campo, cuando el problema es de validación. */
            errores?: {
                campo: string;
                mensaje: string;
            }[];
        };
        /**
         * @description El monto va como cadena decimal, no como número. En JSON los números son de
         *     coma flotante y 80000.10 no se representa exactamente; con dinero eso acaba
         *     en un céntimo de diferencia entre lo que se cobra y lo que se muestra. La
         *     columna del esquema es `numeric`, que sí es exacta, y una cadena la preserva
         *     de extremo a extremo.
         */
        Dinero: {
            /** @example 80000.00 */
            monto: string;
            /**
             * @description Código ISO 4217.
             * @example COP
             */
            moneda: string;
        };
        Servicio: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            sede_id: string;
            nombre: string;
            descripcion?: string;
            /** @description Duración en minutos. */
            duracion_min: number;
            precio: components["schemas"]["Dinero"];
            estado: components["schemas"]["EstadoCatalogo"];
        };
        ListaServicios: {
            datos: components["schemas"]["Servicio"][];
        };
        /**
         * @description Intervalo semiabierto `[inicio, fin)`. El límite inferior entra, el superior
         *     no.
         *
         *     No es un detalle de estilo: con ambos límites cerrados, 10:00–11:00 y
         *     11:00–12:00 comparten un instante, el operador `&&` de PostgreSQL las declara
         *     solapadas y la restricción EXCLUDE rechazaría dos citas consecutivas
         *     perfectamente válidas.
         */
        Periodo: {
            /** Format: date-time */
            inicio: string;
            /** Format: date-time */
            fin: string;
        };
        Franja: {
            periodo: components["schemas"]["Periodo"];
            /** Format: uuid */
            recurso_id: string;
        };
        Disponibilidad: {
            /** Format: uuid */
            servicio_id: string;
            franjas: components["schemas"]["Franja"][];
            /**
             * Format: date-time
             * @description Cuándo se calculó esta vista. El cliente puede saber así cuánta
             *     desactualización está viendo, dentro de los 2 s que RNF-10 permite.
             */
            calculada_en: string;
        };
        /**
         * @description Pide un código al correo con el que se reservó.
         *
         *     La respuesta es SIEMPRE la misma exista o no ese correo (RF-12 A12). Una
         *     respuesta que los distinguiera convertiría esta ruta en un buscador de
         *     clientes del negocio: se prueban direcciones y las que contesten distinto
         *     son las que reservaron.
         */
        SolicitudCodigo: {
            /**
             * Format: email
             * @description El correo con el que se hizo la reserva.
             * @example ana@ejemplo.test
             */
            destino: string;
        };
        CanjeCodigo: {
            /** Format: email */
            destino: string;
            /**
             * @description Los seis dígitos recibidos. Un solo uso y tres intentos (RF-12 A2):
             *     agotados, el código se quema y hay que pedir otro.
             * @example 042317
             */
            codigo: string;
        };
        /**
         * @description Lo que se entrega al acertar el código.
         *
         *     Es de vigencia corta y no se puede revocar: un invitado no tiene sesión que
         *     gestionar, así que la única defensa de este token es que caduque pronto. Por
         *     eso viaja `expira_en`: la interfaz puede pedir que se identifique otra vez
         *     ANTES de que falle una petición, en vez de después.
         */
        TokenAcceso: {
            /** @description Se manda en la cabecera `Authorization: Bearer <token>`. */
            token: string;
            /** Format: date-time */
            expira_en: string;
        };
        /**
         * @description Estados de RF-28.
         * @enum {string}
         */
        EstadoReserva: "pendiente" | "confirmada" | "en_curso" | "completada" | "cancelada" | "no_show" | "expirada";
        Contacto: {
            nombre: string;
            /** Format: email */
            email: string;
            telefono?: string;
        };
        Reserva: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            servicio_id: string;
            /** Format: uuid */
            recurso_id: string;
            periodo: components["schemas"]["Periodo"];
            estado: components["schemas"]["EstadoReserva"];
            precio_cobrado: components["schemas"]["Dinero"];
            contacto?: components["schemas"]["Contacto"];
            /**
             * Format: date-time
             * @description Solo mientras el estado es `pendiente`. Pasado ese instante el cupo
             *     puede liberarse (RF-27).
             */
            expira_en?: string;
            /** Format: date-time */
            creada_en: string;
        };
        ListaReservas: {
            datos: components["schemas"]["Reserva"][];
            /** @description Ausente cuando no hay más páginas. */
            siguiente_cursor?: string;
        };
        NuevaReserva: {
            /** Format: uuid */
            servicio_id: string;
            /** Format: uuid */
            recurso_id: string;
            periodo: components["schemas"]["Periodo"];
            contacto: components["schemas"]["Contacto"];
            /** @description Código de descuento, si aplica (RF-08). */
            voucher_codigo?: string;
        };
        /**
         * @description Lo que devuelve la ruta crítica: la reserva ya con el cupo garantizado, más
         *     el secreto que el cliente necesita para confirmar el pago contra Stripe
         *     directamente, sin que el importe pase por este backend.
         */
        ReservaCreada: {
            reserva: components["schemas"]["Reserva"];
            /** @description `client_secret` del PaymentIntent de Stripe. */
            pago_client_secret?: string;
        };
        /**
         * @description Comprobante de pago (RF-34). El documento vive en el almacén de objetos, no
         *     en esta respuesta: lo que se entrega es un enlace firmado y de vida corta.
         */
        Comprobante: {
            /**
             * @description Correlativo por negocio y año.
             * @example 2026-000042
             */
            numero: string;
            /** @enum {string} */
            tipo: "pago" | "nota_credito";
            /** Format: date-time */
            emitido_en: string;
            /**
             * Format: uri
             * @description Enlace firmado al documento. Ausente mientras el documento todavía no se
             *     haya subido: la fila del comprobante se emite dentro de la transacción y
             *     el objeto se sube después, así que hay una ventana —de segundos— en la
             *     que el comprobante existe y el PDF no.
             */
            url?: string;
            /**
             * Format: date-time
             * @description Cuándo caduca el enlace. Corto a propósito: un enlace firmado es una
             *     credencial, y una credencial que no caduca es una credencial que se
             *     reenvía por chat y sigue sirviendo un año después.
             */
            url_expira_en?: string;
        };
        /**
         * @description Pedir la intención de pago de una reserva ya creada. Nada más: el importe
         *     NO viaja aquí. Lo calcula el servidor desde el precio que la reserva congeló
         *     al crearse (RF-31), porque un importe que llega del cliente es un importe
         *     que el cliente elige.
         */
        SolicitudIntencion: {
            /** Format: uuid */
            reserva_id: string;
        };
        /**
         * @description Estado del intento de cobro (ER-03).
         * @enum {string}
         */
        EstadoPago: "iniciado" | "confirmado" | "fallido";
        /**
         * @description Lo que el navegador necesita para cobrar contra Stripe sin que la tarjeta
         *     pase por este backend (RNF-05).
         *
         *     Pedirla dos veces para la misma reserva devuelve la MISMA intención, no una
         *     nueva: el índice `pago_un_intento_vivo_por_reserva` lo garantiza en el
         *     motor. Sin eso, dos pestañas abiertas crearían dos PaymentIntent y se
         *     podrían pagar los dos.
         */
        IntencionPago: {
            /**
             * @description `client_secret` del PaymentIntent. Es una credencial de un solo
             *     propósito y de una sola reserva: solo sirve para confirmar ESE cobro, y
             *     no permite leer ni mover nada más en la cuenta de Stripe.
             */
            client_secret: string;
            /**
             * @description Clave publicable de Stripe (`pk_...`), la que inicializa Stripe.js.
             *
             *     Viaja en la respuesta y no en una variable de compilación del frontend a
             *     propósito: la clave es del entorno, no del artefacto. Empotrarla al
             *     construir obliga a un build distinto por entorno y a redesplegar el
             *     frontend para rotarla. Es publicable —está pensada para vivir en el
             *     navegador— así que no hay nada que proteger al enviarla.
             */
            clave_publicable: string;
            monto: components["schemas"]["Dinero"];
            estado: components["schemas"]["EstadoPago"];
            /**
             * Format: date-time
             * @description Cuándo vence el bloqueo de la reserva (RF-27). Se repite aquí porque es
             *     lo que decide si vale la pena empezar a pagar: el reloj es parte del
             *     producto, no un detalle del flujo.
             */
            expira_en?: string;
        };
        /**
         * @description Dónde está la confirmación asíncrona de RF-33.
         *
         *     Existe porque el pago se confirma por webhook, fuera del presupuesto de
         *     latencia del núcleo: cuando Stripe.js devuelve "succeeded" al navegador, la
         *     reserva todavía puede estar `pendiente` durante unos cientos de
         *     milisegundos. Sin esta ruta, la interfaz no tiene forma de saber cuándo
         *     dejar de esperar.
         *
         *     Es pública, igual que crear la reserva: quien pregunta ya tiene el
         *     identificador de una reserva que acaba de crear, y la respuesta no dice nada
         *     que no sea suyo. No devuelve el contacto ni el importe.
         */
        EstadoConfirmacion: {
            reserva_estado: components["schemas"]["EstadoReserva"];
            pago_estado?: components["schemas"]["EstadoPago"];
            /**
             * @description Lo que dijo el proveedor cuando el cobro no salió. Presente solo con
             *     `pago_estado = fallido`, y con el texto de Stripe tal cual: reescribirlo
             *     aquí produciría dos vocabularios para el mismo rechazo.
             */
            motivo_fallo?: string;
        };
    };
    responses: {
        /** @description La petición está mal formada */
        PeticionInvalida: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problema"];
            };
        };
        /** @description Error no previsto */
        ErrorInterno: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problema"];
            };
        };
        /**
         * @description No existe. Bajo RLS, "no existe" y "existe pero es de otro tenant" son
         *     indistinguibles, y así debe ser: distinguirlos filtraría la existencia de
         *     datos ajenos.
         */
        NoEncontrado: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problema"];
            };
        };
        /** @description Se superó la cuota de la cuenta o del agente (RNF-08) */
        DemasiadasPeticiones: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problema"];
            };
        };
        /**
         * @description Falta el token de acceso, o ya no vale. No distingue entre "no lo mandaste"
         *     y "el que mandaste está mal": para quien prueba tokens, saber cuál de las
         *     dos cosas falló es la mitad del trabajo hecho.
         *
         *     El vencimiento SÍ se distingue en el `type` del problema, y no es una
         *     contradicción: caducar no es un fallo de quien lo presenta, es el
         *     funcionamiento normal, y la interfaz tiene que poder decir "vuelve a
         *     identificarte" en vez de "no eres tú".
         */
        NoAutorizado: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problema"];
            };
        };
        /** @description Sintácticamente válida pero viola una regla de negocio */
        NoProcesable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problema"];
            };
        };
    };
    parameters: {
        /**
         * @description Tenant sobre el que se opera. Provisional: en cuanto exista autenticación
         *     (RF-12) el tenant se deriva del token y esta cabecera desaparece. Aceptarla
         *     de un cliente en producción permitiría leer los datos de cualquier otro
         *     tenant.
         */
        Tenant: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listarSedes: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Tenant sobre el que se opera. Provisional: en cuanto exista autenticación
                 *     (RF-12) el tenant se deriva del token y esta cabecera desaparece. Aceptarla
                 *     de un cliente en producción permitiría leer los datos de cualquier otro
                 *     tenant.
                 */
                "X-Tenant-Id": components["parameters"]["Tenant"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado de sedes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListaSedes"];
                };
            };
            400: components["responses"]["PeticionInvalida"];
            500: components["responses"]["ErrorInterno"];
        };
    };
    listarServicios: {
        parameters: {
            query?: {
                sede_id?: string;
            };
            header: {
                /**
                 * @description Tenant sobre el que se opera. Provisional: en cuanto exista autenticación
                 *     (RF-12) el tenant se deriva del token y esta cabecera desaparece. Aceptarla
                 *     de un cliente en producción permitiría leer los datos de cualquier otro
                 *     tenant.
                 */
                "X-Tenant-Id": components["parameters"]["Tenant"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado de servicios */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListaServicios"];
                };
            };
            400: components["responses"]["PeticionInvalida"];
            500: components["responses"]["ErrorInterno"];
        };
    };
    consultarDisponibilidad: {
        parameters: {
            query: {
                servicio_id: string;
                /** @description Instante inicial, inclusive. */
                desde: string;
                /** @description Instante final, exclusive. */
                hasta: string;
            };
            header: {
                /**
                 * @description Tenant sobre el que se opera. Provisional: en cuanto exista autenticación
                 *     (RF-12) el tenant se deriva del token y esta cabecera desaparece. Aceptarla
                 *     de un cliente en producción permitiría leer los datos de cualquier otro
                 *     tenant.
                 */
                "X-Tenant-Id": components["parameters"]["Tenant"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Franjas libres */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Disponibilidad"];
                };
            };
            400: components["responses"]["PeticionInvalida"];
            404: components["responses"]["NoEncontrado"];
            500: components["responses"]["ErrorInterno"];
        };
    };
    solicitarCodigo: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Tenant sobre el que se opera. Provisional: en cuanto exista autenticación
                 *     (RF-12) el tenant se deriva del token y esta cabecera desaparece. Aceptarla
                 *     de un cliente en producción permitiría leer los datos de cualquier otro
                 *     tenant.
                 */
                "X-Tenant-Id": components["parameters"]["Tenant"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitudCodigo"];
            };
        };
        responses: {
            /**
             * @description Aceptado. NO significa que el correo exista ni que se haya entregado
             *     nada: significa que si existe, el código va en camino. Es un 202 y no
             *     un 200 justamente porque no se puede afirmar el resultado sin
             *     filtrarlo.
             */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["PeticionInvalida"];
            429: components["responses"]["DemasiadasPeticiones"];
            500: components["responses"]["ErrorInterno"];
        };
    };
    canjearCodigo: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Tenant sobre el que se opera. Provisional: en cuanto exista autenticación
                 *     (RF-12) el tenant se deriva del token y esta cabecera desaparece. Aceptarla
                 *     de un cliente en producción permitiría leer los datos de cualquier otro
                 *     tenant.
                 */
                "X-Tenant-Id": components["parameters"]["Tenant"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CanjeCodigo"];
            };
        };
        responses: {
            /** @description Código correcto */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenAcceso"];
                };
            };
            400: components["responses"]["PeticionInvalida"];
            /**
             * @description El código no vale: equivocado, caducado, ya usado o inexistente. Los
             *     cuatro casos responden igual, porque cada distinción le diría a quien
             *     esté probando códigos si va por buen camino.
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
            429: components["responses"]["DemasiadasPeticiones"];
            500: components["responses"]["ErrorInterno"];
        };
    };
    listarReservas: {
        parameters: {
            query?: {
                estado?: components["schemas"]["EstadoReserva"][];
                desde?: string;
                hasta?: string;
                limite?: number;
                /**
                 * @description Cursor opaco de la página siguiente. Paginación por cursor y no por
                 *     desplazamiento: con OFFSET, insertar una fila mientras se pagina
                 *     desplaza el resto y el cliente ve duplicados o se salta filas.
                 */
                cursor?: string;
            };
            header: {
                /**
                 * @description Tenant sobre el que se opera. Provisional: en cuanto exista autenticación
                 *     (RF-12) el tenant se deriva del token y esta cabecera desaparece. Aceptarla
                 *     de un cliente en producción permitiría leer los datos de cualquier otro
                 *     tenant.
                 */
                "X-Tenant-Id": components["parameters"]["Tenant"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de reservas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListaReservas"];
                };
            };
            400: components["responses"]["PeticionInvalida"];
            401: components["responses"]["NoAutorizado"];
            500: components["responses"]["ErrorInterno"];
        };
    };
    crearReserva: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Tenant sobre el que se opera. Provisional: en cuanto exista autenticación
                 *     (RF-12) el tenant se deriva del token y esta cabecera desaparece. Aceptarla
                 *     de un cliente en producción permitiría leer los datos de cualquier otro
                 *     tenant.
                 */
                "X-Tenant-Id": components["parameters"]["Tenant"];
                /**
                 * @description Clave única de la operación. Obligatoria, no opcional: un agente que
                 *     reintenta un POST tras un timeout crearía dos bloqueos que nadie
                 *     libera hasta el TTL. Repetir la misma clave devuelve la reserva ya
                 *     creada en vez de crear otra.
                 */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NuevaReserva"];
            };
        };
        responses: {
            /** @description Reserva creada, pendiente de pago */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservaCreada"];
                };
            };
            400: components["responses"]["PeticionInvalida"];
            404: components["responses"]["NoEncontrado"];
            /**
             * @description El horario ya está tomado. Es la respuesta al rechazo de la
             *     restricción EXCLUDE por otra transacción concurrente: no es un error
             *     del cliente ni del servidor, es el resultado normal de perder una
             *     carrera por el mismo cupo.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
            422: components["responses"]["NoProcesable"];
            429: components["responses"]["DemasiadasPeticiones"];
            500: components["responses"]["ErrorInterno"];
        };
    };
    obtenerReserva: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Tenant sobre el que se opera. Provisional: en cuanto exista autenticación
                 *     (RF-12) el tenant se deriva del token y esta cabecera desaparece. Aceptarla
                 *     de un cliente en producción permitiría leer los datos de cualquier otro
                 *     tenant.
                 */
                "X-Tenant-Id": components["parameters"]["Tenant"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description La reserva */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reserva"];
                };
            };
            401: components["responses"]["NoAutorizado"];
            404: components["responses"]["NoEncontrado"];
            500: components["responses"]["ErrorInterno"];
        };
    };
    cancelarReserva: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Tenant sobre el que se opera. Provisional: en cuanto exista autenticación
                 *     (RF-12) el tenant se deriva del token y esta cabecera desaparece. Aceptarla
                 *     de un cliente en producción permitiría leer los datos de cualquier otro
                 *     tenant.
                 */
                "X-Tenant-Id": components["parameters"]["Tenant"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description La reserva, ya cancelada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reserva"];
                };
            };
            401: components["responses"]["NoAutorizado"];
            404: components["responses"]["NoEncontrado"];
            /**
             * @description La reserva ya no está en un estado que se pueda cancelar: ya estaba
             *     cancelada, ya se completó, o el bloqueo expiró solo.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
            422: components["responses"]["NoProcesable"];
            500: components["responses"]["ErrorInterno"];
        };
    };
    obtenerComprobante: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Tenant sobre el que se opera. Provisional: en cuanto exista autenticación
                 *     (RF-12) el tenant se deriva del token y esta cabecera desaparece. Aceptarla
                 *     de un cliente en producción permitiría leer los datos de cualquier otro
                 *     tenant.
                 */
                "X-Tenant-Id": components["parameters"]["Tenant"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description El comprobante, con un enlace firmado al documento */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comprobante"];
                };
            };
            401: components["responses"]["NoAutorizado"];
            /**
             * @description No hay comprobante. Puede ser que la reserva no exista, que no sea de
             *     quien pregunta, o que todavía no se haya emitido porque el pago no se
             *     confirmó. Los tres responden igual por la misma razón de siempre.
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
            500: components["responses"]["ErrorInterno"];
        };
    };
    crearIntencionPago: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Tenant sobre el que se opera. Provisional: en cuanto exista autenticación
                 *     (RF-12) el tenant se deriva del token y esta cabecera desaparece. Aceptarla
                 *     de un cliente en producción permitiría leer los datos de cualquier otro
                 *     tenant.
                 */
                "X-Tenant-Id": components["parameters"]["Tenant"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitudIntencion"];
            };
        };
        responses: {
            /** @description La intención de pago, nueva o la que ya existía */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntencionPago"];
                };
            };
            400: components["responses"]["PeticionInvalida"];
            404: components["responses"]["NoEncontrado"];
            /**
             * @description La reserva ya no admite pago: venció su bloqueo, ya está confirmada, o
             *     se canceló. No es un fallo de la petición, es que llegó tarde.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
            429: components["responses"]["DemasiadasPeticiones"];
            500: components["responses"]["ErrorInterno"];
            /**
             * @description El proveedor de pago no respondió o respondió con un error. Es un 502 y
             *     no un 500 porque la distinción importa para operar: el fallo está
             *     aguas arriba, en Stripe, no en este sistema, y la reserva sigue
             *     apartada hasta que venza.
             */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problema"];
                };
            };
        };
    };
    consultarConfirmacion: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Tenant sobre el que se opera. Provisional: en cuanto exista autenticación
                 *     (RF-12) el tenant se deriva del token y esta cabecera desaparece. Aceptarla
                 *     de un cliente en producción permitiría leer los datos de cualquier otro
                 *     tenant.
                 */
                "X-Tenant-Id": components["parameters"]["Tenant"];
            };
            path: {
                reserva_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dónde está la confirmación */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstadoConfirmacion"];
                };
            };
            400: components["responses"]["PeticionInvalida"];
            404: components["responses"]["NoEncontrado"];
            500: components["responses"]["ErrorInterno"];
        };
    };
}
